name: CI
on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  master:
    name: 'master'
    runs-on: 'ghcr.io/cirruslabs/ubuntu-runner-amd64:24.04-lg'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      # - name: Expose GitHub Runtime
      #   uses: crazy-max/ghaction-github-runtime@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        # env:
        #   BUILDKIT_PROGRESS: plain
        #   BUILDX_EXPERIMENTAL: 1
        #   ACTIONS_STEP_DEBUG: true
        with:
          context: ./master
          file: ./master/Dockerfile
          tags: "testing/bitcoin:latest"
          cache-from: type=gha,url=http://127.0.0.1:12321/
          cache-to: type=gha,url=http://127.0.0.1:12321/,mode=max
          # load: true
          # push: false
